# Generated by Django 4.1.3 on 2023-06-21 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_pedido_estado_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorasDiponibles',
            fields=[
                ('id_Hora', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('hora', models.TimeField()),
                ('hora_is_active', models.BooleanField(default=True)),
                ('row_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=50, null=True)),
                ('serv_is_active', models.BooleanField(default=True)),
                ('row_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.BigAutoField(primary_key=True, serialize=False)),
                ('fk_id_horadisponible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.horasdiponibles')),
                ('fk_id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='horasdiponibles',
            name='fk_id_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicio'),
        ),
    ]
